# Generated by Django 3.1 on 2023-02-23 09:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230219_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_avatar_path, verbose_name='アバター'),
        ),
    ]
