# Generated by Django 3.1 on 2023-04-08 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.CharField(max_length=300, verbose_name='説明')),
                ('status', models.IntegerField(choices=[(1, '新規'), (2, '作業中'), (3, '完了')], default=1, verbose_name='ステータス')),
                ('progress', models.IntegerField(choices=[(1, '0%'), (2, '10%'), (3, '20%'), (4, '30%'), (5, '40%'), (6, '50%'), (7, '60%'), (8, '70%'), (9, '80%'), (10, '90%'), (11, '100%')], default=1, verbose_name='進捗')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='タスク開始時間')),
                ('total_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='合計作業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category', verbose_name='カテゴリー')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL, verbose_name='タスク作成者')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'ordering': ['-created_at'],
            },
        ),
    ]
