# Generated by Django 3.1 on 2023-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230408_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '新規'), (2, '進行中'), (3, '完了')], default=1, verbose_name='ステータス'),
        ),
    ]
