# Generated by Django 3.1 on 2023-03-21 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20230223_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.CharField(max_length=300, verbose_name='説明')),
                ('status', models.IntegerField(choices=[(0, '新規'), (1, '作業中'), (2, '完了')], default=0, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='タスク開始時間')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='タスク一時停止時間')),
                ('total_time', models.DurationField(default=0, verbose_name='合計作業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category', verbose_name='カテゴリー')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL, verbose_name='タスク作成者')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
            },
        ),
    ]
