# Generated by Django 3.1 on 2023-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='total_time',
            field=models.DurationField(blank=True, default=0, null=True, verbose_name='合計作業時間'),
        ),
    ]
