# Generated by Django 3.1 on 2023-03-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20230324_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'タスク', 'verbose_name_plural': 'タスク'},
        ),
    ]
